version: '3.5'

services:
  postgres:
    container_name: rn_postgres
    image: postgres
    hostname: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rn2020
      POSTGRES_DB: rnmonitor
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rnnetwork
    restart: unless-stopped
  pgadmin:
    container_name: rn_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - rnnetwork
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
  pdi:
    container_name: pdi
    image andrespp:pdi
    ports:
      - "8181"
    links:
      - postgres
    networks:
      - rnnetwork
volumes:
  pgadmin:
  postgres-data:
networks:
  rnnetwork:
    driver: bridge
