version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB:   rnmonitor
    ports:
      - "5432:5432"
    volumes:
      - /var/postgres/data:/var/lib/postgressql/data
    networks:
      - postgresql
  rnmonitor-pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rolando.a@sapo.pt
      PGADMIN_DEFAULT_PASSWORD: rnmonitor2020
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - postgresql

networks:
  postgresql:
    driver: bridge
