version: '3'

services:
  rnmonitor-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: rnmonitor2019
      POSTGRES_USER: postgres
      POSTGRES_DB:   rnmonitor
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgressql/data
    networks:
      - compose-network
  rnmonitor-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: rolando.a@sapo.pt
      PGADMIN_DEFAULT_PASSWORD: rnmonitor2019
    ports:
      - "80:80"
    depends_on:
      - rnmonitor-postgres
    networks:
      - compose-network

networks:
  compose-network:
    driver: bridge
