version: '3.1'

services:
  postgres:
    container_name: rn_postgres
    image: postgres
    hostname: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rnmonitor
    volumes:
      - ./data/pdgata:/var/lib/postgresql/data
    networks:
      - rnnetwork
    restart: unless-stopped
  pgadmin:
    container_name: rn_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    networks:
      - rnnetwork
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
networks:
  rnnetwork:
    driver: bridge
