version: '3.5'

services:
  postgres:
    container_name: rn_postgres
    image: postgres
    hostname: postgres
    ports:
      - "15432:5432"
    expose:
      - "15432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rn2020
      POSTGRES_DB: rnmonitor
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rn_network
    restart: unless-stopped
  pgadmin:
    container_name: rn_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - rn_network
    restart: unless-stopped
networks:
  rn_network:
    driver: bridge
volumes:
  pgadmin:
  postgres-data:
